/var/mobile/postinst/.theos/obj/debug/armv7/main.m.0b84edfb.o: main.m \
  /var/theos/Prefix.pch /var/theos/include/_Prefix/BackwardsCompat.h \
  /var/theos/include/_Prefix/IOSMacros.h /var/theos/include/HBLog.h \
  /var/theos/include/CoreFoundation/CFLogUtilities.h

/var/theos/Prefix.pch:

/var/theos/include/_Prefix/BackwardsCompat.h:

/var/theos/include/_Prefix/IOSMacros.h:

/var/theos/include/HBLog.h:

/var/theos/include/CoreFoundation/CFLogUtilities.h:
